#!/bin/bash
set -euo pipefail

# Cross-OS wapper for unity-meta-check. Supported OS: macOS/Linux/Windows

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
DARWIN_64_DIR="${BASE_DIR}/darwin-amd64"
LINUX_64_DIR="${BASE_DIR}/linux-amd64"
WINDOWS_64_DIR="${BASE_DIR}/windows-amd64"


throw() {
  local message="$*"
  printf "${message}\n" 1>&2
  false
}


main() {
	local os
	local arch
	local suffix

	case "$OSTYPE" in
		darwin*)
			os=darwin
			suffix=""
			;;
		linux*)
			os=linux
			suffix=""
			;;
		msys | cygwin | win32)
			os=windows
			suffix=".exe"
			;;
		*)
			throw "unsupported os: $OSTYPE"
			;;
	esac

	local m="$(uname -m)"
	case "$m" in
		arm64)
			arch=arm64
			;;
		aarch64)
			arch=amd64
			;;
		*)
			throw "unsupported arch: $m"
			;;
	esac

	"${BASE_DIR}/${os}-${arch}/unity-meta-check${suffix}"
}


main "$@"
