#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"


throw() {
	local message="$*"
	printf "$message" 1>&2
	false
}


main() {
	local target_dir="$1"
	local os
	local arch

	[[ -d "$target_dir" ]] || throw "no such a directory: $target_dir"

	case "$OSTYPE" in
		darwin*)
			os=darwin
			;;
		linux*)
			os=linux
			;;
		msys | cygwin | win32)
			os=windows
			;;
		*)
			throw "unsupported os: $OSTYPE"
			;;
	esac

	local m="$(uname -m)"
	case "$m" in
		arm64)
			arch=arm64
			;;
		aarch64)
			arch=amd64
			;;
		*)
			throw "unsupported arch: $m"
			;;
	esac

	find "${BASE_DIR}/${os}-${arch}" -type f -print0 | xargs -0 -I{} cp -av {} "$target_dir/"
}


main "$@"
