#!/bin/bash
set -xeuo pipefail

BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
TMP_DIR="${BASE_DIR}/tmp"

LINUX_AMD64_DIR="${BASE_DIR}/linux-amd64"
DARWIN_AMD64_DIR="${BASE_DIR}/darwin-amd64"
WINDOWS_AMD64_DIR="${BASE_DIR}/windows-amd64"


main() {
	local revision="$1"
	local outdir="${BASE_DIR}"
	local workspace="${TMP_DIR}/${revision}"

	mkdir -p "$TMP_DIR"
	if [[ -d "$workspace" ]]; then
		(cd "$workspace"; git fetch --prune)
	else
		git clone git@github.com:DeNA/unity-meta-check "$workspace"
	fi

	(cd "$workspace"
			git checkout -f "$revision"
			git submodule update --init --recursive
			make test clean all

			mkdir -p "$LINUX_AMD64_DIR"
			while read binpath; do
				local short_basename="$(basename "$binpath" | sed 's/-linux-amd64$//')"
				mv "$binpath" "${LINUX_AMD64_DIR}/${short_basename}"
			done < <(find ./dist -name '*-linux-amd64')

			mkdir -p "$DARWIN_AMD64_DIR"
			while read binpath; do
				local short_basename="$(basename "$binpath" | sed 's/-darwin-amd64$//')"
				mv "$binpath" "${DARWIN_AMD64_DIR}/${short_basename}"
			done < <(find ./dist -name '*-darwin-amd64')

			mkdir -p "$WINDOWS_AMD64_DIR"
			while read binpath; do
				local short_basename="$(basename "$binpath" | sed 's/-windows-amd64\.exe$/.exe/')"
				mv "$binpath" "${WINDOWS_AMD64_DIR}/${short_basename}"
			done < <(find ./dist -name '*-windows-amd64.exe')
	)
}


main "$@"
